data=read.table("household_power_consumption.txt",header=TRUE, sep=";",na.strings = "?",stringsAsFactors = FALSE)
mydata=subset(data,data$Date=="1/2/2007" | data$Date=="2/2/2007")
mydata$Date=as.Date(mydata$Date, format= "%d/%m/%Y")
mydata$DateTime <- as.POSIXct(paste(mydata$Date,mydata$Time))
par(mfrow=c(2,2))
plot(mydata$Global_active_power~mydata$DateTime,type="l",ylab="Global Active Power",xlab="")
plot(mydata$Voltage~mydata$DateTime,type="l",xlab="datetime",ylab = "Voltage")
plot(mydata$Sub_metering_1~mydata$DateTime,type="l")
lines(mydata$Sub_metering_2~mydata$DateTime,col="red")
lines(mydata$Sub_metering_3~mydata$DateTime,col="blue")
legend("topright", col=c("black", "red","blue"), lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(mydata$Global_reactive_power~mydata$DateTime,type="l",ylab="Global Reactive Power",xlab = "datetime")
dev.copy(png,filename="plot4.png")
dev.off()
