data=read.table("household_power_consumption.txt",header=TRUE, sep=";",na.strings = "?",stringsAsFactors = FALSE)
mydata=subset(data,data$Date=="1/2/2007" | data$Date=="2/2/2007")
mydata$Time=strptime(mydata$Time,format="%H:%M:%S")
mydata$Date=as.Date(mydata$Date, format= "%d/%m/%Y")
par(mfrow=c(2,2))
plot(mydata$Time,mydata$Global_active_power,type="l",ylab="Global Active Power")
plot(mydata$Time,mydata$Voltage,type="l",xlab="datetime",ylab = "Voltage")
plot(mydata$Time,mydata$Sub_metering_1,type="l")
lines(mydata$Time,mydata$Sub_metering_2,col="red")
lines(mydata$Time,mydata$Sub_metering_3,col="blue")
legend("topright", col=c("black", "red","blue"), lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(mydata$Time,mydata$Global_reactive_power,type="l",ylab="Global Reactive Power",xlab = "datetime")
dev.copy(png,filename="plot4.png")
dev.off()
